# Generated by Django 3.2.19 on 2024-04-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniforme',
            name='upreço',
            field=models.IntegerField(default=0),
        ),
    ]
