# Generated by Django 3.2.19 on 2024-04-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
